### PR TITLE
Fix dynamicvar incorrect parsing on bool values

### LINKED ISSUE #150: DynamicVar incorrect parsing on bool values
when we pass `t,f,true,false,0,1` as dynamic flag values, always returns default value.

ex:
```console
...
flagset.DynamicVar(&options.hasPoc, "poc", "true", "display cves that has public published poc"),
...
$ go run . -poc=false  # hasPoc = true
$ go run . -poc #haPoc=true
```

expected:
```console
$ go run . -poc=false  # hasPoc = false
$ go run . -poc # haPoc=true
```

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
- closes #150

### CODE REVIEW

File: dynamic_var.go [hunk 1]
```diff
@@ -16,19 +16,24 @@ type dynamicFlag struct {
...
 	fieldKind := reflect.TypeOf(df.field).Elem().Kind()
-	var isBoolValue bool
-	if _, err := strconv.ParseBool(value); err == nil {
-		isBoolValue = true
-	}
-	if fieldKind == reflect.Bool && isBoolValue {
-		boolField := df.field.(*bool)
-		*boolField = true
-		return nil
+	var (
```
Comment (dogancanbakir) [inline dynamic_var.go:19]: Can we add some tests, please? Thanks!

File: dynamic_var.go [hunk 2]
```diff
@@ -16,19 +16,24 @@ type dynamicFlag struct {
...
+	)
+	if value == "t" || value == "T" || value == "true" || value == "TRUE" {
+		pv = true
+		optionWithoutValue = true
+	} else if value == "f" || value == "F" || value == "false" || value == "FALSE" {
+		pv = false
 	}
+
 	switch fieldKind {
+	case reflect.Bool:
```
Comment (dogancanbakir) [inline dynamic_var.go:31]: We can leverage type abstractions instead of relying on reflection, e.g. https://github.com/projectdiscovery/utils/pull/266/files#diff-1e4c1fcda16b2f94c80249aa8e58bff941c8621fe28458d767fd3502c10c4f31R27

**Review by dogancanbakir — CHANGES_REQUESTED** [review]

**Review by dogancanbakir — APPROVED** [review]
LGTM

**Review by ehsandeep — APPROVED** [review]
